#index:
#    path: /
#    controller: App\Controller\DefaultController::index

admin_create_category:
  path: /admin/category/create
  controller: App\Controller\AdminCategoryController::createCategory
  methods: POST
